$("#modal1").click(()=>(window.location.href='../pages/Mapa.html'))
$("#modal2").click(()=>(window.location.href='../pages/Mapa.html'))
$("#modal3").click(()=>(window.location.href='../pages/Mapa.html'))
$("#modal4").click(()=>(window.location.href='../pages/Mapa.html'))
$("#modal5").click(()=>(window.location.href='../pages/Mapa.html'))
$("#modal6").click(()=>(window.location.href='../pages/Mapa.html'))